### ISSUE TITLE
Notebook 09: skimage.external no longer exists

### ISSUE THREAD

**Issue by paucabar** [guiwitz/neubias_academy_biapy#1]
Hi Guillaume,

It seems that skimage.external has been deprecated, so one gets an error when trying to import it like in your Pattern_matching notebook:

`from skimage import tiffFile`

Instead, one can simply do:

`import tifffile`

That fixed the issue for me and I was able to run the whole Notebook.

Best wishes,
Pau

**Comment by guiwitz** [comment]
Finally fixed that issue with #[8564f1b](https://github.com/guiwitz/neubias_academy_biapy/commit/8564f1ba9f2fd1bda29021954e6254dd27e248c0). Thanks for the issue!
